dist: xenial

language: python

python:
    - "3.7"

deploy:
    provider: lambda
    function_name: "RomanNumeralsToArabic"
    region: "eu-west-2"
    role: "arn:aws:iam::255446756174:role/lambda_invoke_function_assume_apigw_role"
    runtime: "python3.7"
    handler: "lambda_function.lambda_handler"
