dist: xenial

language: python

python:
    - "3.7"

before_install:
    pip3 install pipenv

install:
    pipenv install

script:
    - make test
    - make lint

deploy:
    provider: lambda
    function_name: "RomanNumeralsToArabic"
    region: "eu-west-2"
    role: "arn:aws:iam::255446756174:role/lambda_invoke_function_assume_apigw_role"
    runtime: "python3.7"
    module_name: "roman_numerals"
    handler_name: "lambda_handler"
